AllCops:
  NewCops: enable

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 80

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  CountComments: true
  Max: 25
  IgnoredMethods: []
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 9

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

Naming/RescuedExceptionsVariableName:
  PreferredName: err

Style/AccessorGrouping:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
